//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPlug.Ext.Brainboxes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPlug.Ext.Brainboxes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brainboxes_logo {
            get {
                object obj = ResourceManager.GetObject("brainboxes_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.Brainboxes.Models.Settings.Defaults.DefaultsValues
        ///
        ///&lt;form action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; enctype=&quot;application/x-www-form-urlencoded&quot;&gt;
        ///    &lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///        &lt;div class=&quot;row-fluid&quot;&gt;
        ///            &lt;div class=&quot;box&quot;&gt;
        ///                &lt;div class=&quot;span4&quot;&gt;
        ///                    &lt;a style=&quot;line-height: 52px;&quot; href=&quot;#&quot;&gt;&lt;img alt=&quot;Brainboxes Logo&quot; src=&quot;assets/brainboxes/images/brainboxes.png&quot;&gt;&lt;/a&gt;
        ///                &lt;/div&gt;
        ///                &lt;div class=&quot;span4&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Defaults_html {
            get {
                return ResourceManager.GetString("Defaults_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.Brainboxes.Models.Settings.Device.Device
        ///
        ///@functions{ 
        ///
        ///    public string ColourState( MultiPlug.Base.Exchange.Payload thePayload )
        ///    {
        ///        string Result = &quot;IOStateUnknown&quot;;
        ///
        ///        if (thePayload.Pairs.Length &gt; 0)
        ///        {
        ///            Result = thePayload.Pairs[0].Value == &quot;1&quot; ? &quot;IOStateGreen&quot; : &quot;IOStateRed&quot;;
        ///        }
        ///
        ///        return Result;
        ///    }
        ///}
        ///
        ///&lt;style&gt;
        ///
        ///.IOState{
        ///    padding-left: 5px;
        ///    line-height: 30px;
        ///    border-left-width: 6px;
        ///    border-le [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Device_html {
            get {
                return ResourceManager.GetString("Device_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///$(&apos;#connectbtn&apos;).on(&apos;click&apos;, function (event) {
        ///    event.preventDefault();
        ///    var Group = { Id: ConnectButtonEventId, Pairs: [] };
        ///    $.connection.wS.server.send(Group);
        ///});
        ///
        ///$(&apos;#restartbtn&apos;).on(&apos;click&apos;, function (event) {
        ///    event.preventDefault();
        ///    var Group = { Id: RestartButtonEventId, Pairs: [] };
        ///    $.connection.wS.server.send(Group);
        ///});
        ///
        ///$(&apos;.ToggleOutput&apos;).change(function () {
        ///
        ///    var pair = { &quot;Type&quot;: &quot;value&quot;, &quot;Value&quot;: &quot;0&quot; };
        ///
        ///    if (this.checked) {
        ///        pair = { &quot;Typ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string device_js {
            get {
                return ResourceManager.GetString("device_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.Brainboxes.Models.Settings.Device.NotFound
        ///
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span4&quot;&gt;
        ///                &lt;a style=&quot;line-height: 52px;&quot; href=&quot;#&quot;&gt;&lt;img alt=&quot;Brainboxes Logo&quot; src=&quot;assets/brainboxes/images/brainboxes.png&quot;&gt;&lt;/a&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span4&quot;&gt;
        ///                &lt;p style=&quot;font-size:26px; line-height: 54px; text-align: center; margin: 0px;&quot;&gt;Device Not Found&lt;/p&gt;
        ///            &lt;/div&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeviceNotFound_html {
            get {
                return ResourceManager.GetString("DeviceNotFound_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(&quot;#btn-newdevice&quot;).click(function () {
        ///    $(&apos;#devicesTable tr:last&apos;).after(NewDevice());
        ///
        ///    $(&quot;.btn-deletedevicetemp&quot;).click(function (event) {
        ///        event.preventDefault();
        ///        $(this).closest(&quot;tr&quot;).remove();
        ///    });
        ///
        ///});
        ///
        ///function ApplyDeleteButton() {
        ///
        ///    $(&quot;.btn-deletedevice&quot;).click(function (event) {
        ///        event.preventDefault();
        ///
        ///        var theRow = $(this).closest(&quot;tr&quot;);
        ///
        ///        $.post($(this).attr(&apos;href&apos;), function (data) {
        ///
        ///        })
        ///        .done(function () {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string devices_js {
            get {
                return ResourceManager.GetString("devices_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.Brainboxes.Models.Settings.Discovery.DiscoveryViewModel
        ///
        ///&lt;form action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; enctype=&quot;application/x-www-form-urlencoded&quot;&gt;
        ///    &lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///        &lt;div class=&quot;row-fluid&quot;&gt;
        ///            &lt;div class=&quot;box&quot;&gt;
        ///                &lt;div class=&quot;span4&quot;&gt;
        ///                    &lt;a style=&quot;line-height: 52px;&quot; href=&quot;#&quot;&gt;&lt;img alt=&quot;Brainboxes Logo&quot; src=&quot;assets/brainboxes/images/brainboxes.png&quot;&gt;&lt;/a&gt;
        ///                &lt;/div&gt;
        ///                &lt;div class=&quot;span4&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Discovery_html {
            get {
                return ResourceManager.GetString("Discovery_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///}.
        /// </summary>
        internal static string IOStateColours_css {
            get {
                return ResourceManager.GetString("IOStateColours_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.Brainboxes.Models.SettingsViewModel
        ///
        ///&lt;div class=&quot;row-fluid&quot;&gt;
        ///    &lt;div class=&quot;box&quot;&gt;
        ///        &lt;div class=&quot;span5&quot;&gt;
        ///            &lt;a href=&quot;/&quot;&gt;&lt;img alt=&quot;Brainboxes Logo&quot; src=&quot;assets/brainboxes/images/brainboxes.png&quot;&gt;&lt;/a&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;span2&quot;&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;span3&quot;&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;span2&quot;&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;form class=&quot;form-horizontal&quot; action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; enctype=&quot;application/x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OldSettings_html {
            get {
                return ResourceManager.GetString("OldSettings_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.Brainboxes.Models.Settings.Home.Home
        ///
        ///&lt;form action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; enctype=&quot;application/x-www-form-urlencoded&quot;&gt;
        ///    &lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///        &lt;div class=&quot;row-fluid&quot;&gt;
        ///            &lt;div class=&quot;box&quot;&gt;
        ///                &lt;div class=&quot;span4&quot;&gt;
        ///                    &lt;a style=&quot;line-height: 52px;&quot; href=&quot;#&quot;&gt;&lt;img alt=&quot;Brainboxes Logo&quot; src=&quot;assets/brainboxes/images/brainboxes.png&quot;&gt;&lt;/a&gt;
        ///                &lt;/div&gt;
        ///                &lt;div class=&quot;span4&quot;&gt;
        ///                  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Settings_html {
            get {
                return ResourceManager.GetString("Settings_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.Brainboxes.Models.Settings.Device.Subscription
        ///
        ///&lt;form action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; enctype=&quot;application/x-www-form-urlencoded&quot;&gt;
        ///    &lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///        &lt;div class=&quot;row-fluid&quot;&gt;
        ///            &lt;div class=&quot;box&quot;&gt;
        ///                &lt;div class=&quot;span5&quot;&gt;
        ///                    &lt;a href=&quot;/&quot;&gt;&lt;img alt=&quot;Brainboxes Logo&quot; src=&quot;assets/brainboxes/images/brainboxes.png&quot;&gt;&lt;/a&gt;
        ///                &lt;/div&gt;
        ///                &lt;div class=&quot;span2&quot;&gt;
        ///                    &lt;p style=&quot;font [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Subscription_html {
            get {
                return ResourceManager.GetString("Subscription_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* The switch - the box around the slider */
        ///.switch {
        ///  position: relative;
        ///  display: inline-block;
        ///  width: 59px;
        ///  height: 34px;
        ///}
        ///
        ////* Hide default HTML checkbox */
        ///.switch input {
        ///  opacity: 0;
        ///  width: 0;
        ///  height: 0;
        ///}
        ///
        ///label.switch {
        ///  margin-top: 1px;
        ///  margin-bottom: 1px;
        ///}
        ///
        ////* The slider */
        ///.slider {
        ///  position: absolute;
        ///  cursor: pointer;
        ///  top: 0;
        ///  left: 0;
        ///  right: 0;
        ///  bottom: 0;
        ///  background-color: #ccc;
        ///  -webkit-transition: .4s;
        ///  transition: .4s;
        ///}
        ///
        ///.sli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ToggleSwitch_css {
            get {
                return ResourceManager.GetString("ToggleSwitch_css", resourceCulture);
            }
        }
    }
}
